# Generated by Django 4.2.1 on 2023-05-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Категория напитка',
                'verbose_name_plural': 'Категории напитков',
                'ordering': ['name'],
            },
        ),
    ]
