# Generated by Django 4.2.1 on 2023-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriptionfra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='namefra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom'),
        ),
    ]
