# Generated by Django 4.2.1 on 2023-11-09 10:18

from django.db import migrations, models
import django.db.models.deletion
import quickstart.models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_manufacturer_manufacturer_manufacturer_unique_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=quickstart.models.ForeignKey(blank=True, db_column='country', help_text='страна происхождения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturers', to='quickstart.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='img',
            field=models.ImageField(blank=True, db_column='label', help_text='этикетка', null=True, upload_to='manufacturer/', verbose_name='label'),
        ),
    ]
