# Generated by Django 4.2.1 on 2023-11-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_manufacturer_country_manufacturer_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='www',
            field=models.URLField(blank=True, db_column='www', default=None, null=True, verbose_name='web address'),
        ),
        migrations.AlterField(
            model_name='wineglass',
            name='photo',
            field=models.ImageField(blank=True, db_column='label', null=True, upload_to='glasses/', verbose_name='photo'),
        ),
    ]
