# Generated by Django 4.2.1 on 2023-05-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
                ('alcohol', models.PositiveIntegerField(db_column='alcoholvolume', unique=True, verbose_name='Alcohol by volume')),
            ],
            options={
                'verbose_name': 'Крепость',
                'verbose_name_plural': 'Содержание спирта',
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Wine Bod',
                'verbose_name_plural': 'Wine Bodies',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Страна происхождения',
                'verbose_name_plural': 'Страны происхождения',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Гастрономия',
                'verbose_name_plural': 'Гастрономия',
            },
        ),
        migrations.CreateModel(
            name='ProductionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Способ производства',
                'verbose_name_plural': 'Способы производства',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Сырье',
                'verbose_name_plural': 'Сырье',
            },
        ),
        migrations.CreateModel(
            name='SugarVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
                ('sugar', models.PositiveIntegerField(db_column='sugarvolume', unique=True, verbose_name='Sugar by volume')),
            ],
            options={
                'verbose_name': 'Содержание сахара',
                'verbose_name_plural': 'Содержание сахара',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
                ('raw', models.ForeignKey(blank=True, db_column='rawmaterial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.country', verbose_name='Raw Material')),
            ],
            options={
                'verbose_name': 'Сорт',
                'verbose_name_plural': 'Сорта',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
                ('country', models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Регион происхождения',
                'verbose_name_plural': 'Регионы происхождения',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
                ('brand', models.ForeignKey(blank=True, db_column='brand', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.category', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name', models.CharField(db_column='name_rus', db_index=True, max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='Описание')),
                ('nameeng', models.CharField(db_column='name_eng', db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('descriptioneng', models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='Description')),
                ('namefra', models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='Nom')),
                ('descriptionfra', models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='Description')),
                ('type', models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.type', verbose_name='Type of drink')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
    ]
