# Generated by Django 4.2.1 on 2023-11-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_host_subhost_host_hosts_unique_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, help_text='описание на русском языке', null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='host',
            name='name_rus',
            field=models.CharField(blank=True, db_column='name_rus', db_index=True, help_text='наименование на русском языке', max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='subhost',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, help_text='описание на русском языке', null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='subhost',
            name='name_rus',
            field=models.CharField(blank=True, db_column='name_rus', db_index=True, help_text='наименование на русском языке', max_length=255, null=True, verbose_name='наименование'),
        ),
    ]
