# Generated by Django 4.2.1 on 2023-05-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_remove_potion_appellation_potion_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='food',
            field=models.ManyToManyField(blank=True, db_column='food', related_name='potion_food', to='quickstart.food', verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='potion',
            name='alcohol',
            field=models.PositiveIntegerField(blank=True, db_column='alcoholvolume', null=True, verbose_name='Alcohol by volume'),
        ),
        migrations.AlterField(
            model_name='potion',
            name='sugar',
            field=models.PositiveIntegerField(blank=True, db_column='sugarvolume', null=True, verbose_name='Sugar by volume'),
        ),
    ]
