# Generated by Django 4.2.1 on 2023-11-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_host_description_rus_host_name_rus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subhost',
            name='host',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='SubHost',
        ),
    ]
