# Generated by Django 4.2.1 on 2023-11-13 15:01

from django.db import migrations, models
import django.db.models.deletion
import quickstart.models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_remove_subhost_host_delete_host_delete_subhost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name_rus', models.CharField(blank=True, db_column='name_rus', db_index=True, help_text='наименование на русском языке', max_length=255, null=True, verbose_name='наименование')),
                ('description_rus', models.TextField(blank=True, db_column='description_rus', default=None, help_text='описание на русском языке', null=True, verbose_name='описание')),
                ('name_eng', models.CharField(blank=True, db_column='name_eng', db_index=True, help_text='name in english', max_length=255, null=True, verbose_name='name')),
                ('description_eng', models.TextField(blank=True, db_column='description_eng', default=None, help_text='description in english', null=True, verbose_name='description')),
                ('www', models.URLField(db_column='www', default=None, unique=True, verbose_name='www')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ('name_eng',),
            },
        ),
        migrations.CreateModel(
            name='SubHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name_rus', models.CharField(blank=True, db_column='name_rus', db_index=True, help_text='наименование на русском языке', max_length=255, null=True, verbose_name='наименование')),
                ('description_rus', models.TextField(blank=True, db_column='description_rus', default=None, help_text='описание на русском языке', null=True, verbose_name='описание')),
                ('name_eng', models.CharField(blank=True, db_column='name_eng', db_index=True, help_text='name in english', max_length=255, null=True, verbose_name='name')),
                ('description_eng', models.TextField(blank=True, db_column='description_eng', default=None, help_text='description in english', null=True, verbose_name='description')),
                ('tail', models.CharField(blank=True, db_column='subhost', db_index=True, help_text='sudhost tail', max_length=255, null=True, verbose_name='subhost tail')),
                ('host', quickstart.models.ForeignKey(blank=True, db_column='host', help_text='site_address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subhosts', to='quickstart.host', verbose_name='host')),
            ],
            options={
                'verbose_name': 'SubHost',
                'verbose_name_plural': 'SubHosts',
                'ordering': ('name_eng',),
            },
        ),
        migrations.AddConstraint(
            model_name='host',
            constraint=models.UniqueConstraint(fields=('name_eng', 'www'), name='hosts_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='subhost',
            constraint=models.UniqueConstraint(fields=('name_eng', 'tail'), name='subhosts_unique_index'),
        ),
    ]
