# Generated by Django 4.2.1 on 2023-05-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_alter_category_options_alter_food_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория напитка', 'verbose_name_plural': 'Категории напитков'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='subcategory',
            order_with_respect_to='category',
        ),
    ]
