# Generated by Django 4.2.1 on 2023-11-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_host_subhost_host_hosts_unique_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ('name_eng',), 'verbose_name': 'адресс хоста', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.RemoveField(
            model_name='host',
            name='description_rus',
        ),
        migrations.RemoveField(
            model_name='host',
            name='name_rus',
        ),
        migrations.RemoveField(
            model_name='subhost',
            name='description_rus',
        ),
        migrations.RemoveField(
            model_name='subhost',
            name='name_rus',
        ),
    ]
