# Generated by Django 4.2.1 on 2023-11-14 10:27

from django.db import migrations, models
import django.db.models.deletion
import quickstart.models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_alter_host_options_remove_host_description_rus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datex', models.DateTimeField(auto_now=True, db_column='datex', null=True)),
                ('date1', models.DateTimeField(auto_now_add=True, db_column='datea', null=True)),
                ('name_eng', models.CharField(blank=True, db_column='name_eng', db_index=True, help_text='name in english', max_length=255, null=True, verbose_name='name')),
                ('description_eng', models.TextField(blank=True, db_column='description_eng', default=None, help_text='description in english', null=True, verbose_name='description')),
                ('status', models.PositiveIntegerField(blank=True, db_column='status', db_index=True, help_text='Status code fo HTTP request', null=True, verbose_name='status code')),
                ('agent', models.CharField(blank=True, db_column='agent', db_index=True, help_text='user agent', max_length=255, null=True, verbose_name='user agent')),
                ('subhost', quickstart.models.ForeignKey(blank=True, db_column='subhost', help_text='parser log', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parserlogs', to='quickstart.host', verbose_name='subhost')),
            ],
            options={
                'verbose_name': 'Parser Log',
                'verbose_name_plural': 'Parser Logs',
                'ordering': ('datex', 'subhost'),
            },
        ),
        migrations.AddConstraint(
            model_name='parserlog',
            constraint=models.UniqueConstraint(fields=('name_eng', 'agent'), name='parserlog_unique_index'),
        ),
    ]
