# Generated by Django 4.2.1 on 2023-05-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_alter_food_options_rename_name_alcoholvolume_namerus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-namerus',), 'verbose_name': 'Категория напитка', 'verbose_name_plural': 'Категории напитков'},
        ),
        migrations.AlterField(
            model_name='alcoholvolume',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='body',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='category',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='color',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='country',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='food',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='potion',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='productionmethod',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='region',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='sugarvolume',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='type',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='namerus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='subcategory',
            order_with_respect_to=None,
        ),
    ]
