# Generated by Django 4.2.1 on 2023-11-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_alter_parserlog_subhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserlog',
            name='decoded',
            field=models.BooleanField(db_column='decoded', default=False, verbose_name='decoded'),
        ),
    ]
