# Generated by Django 4.2.1 on 2023-05-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_potion'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_column='year', null=True, verbose_name='Year'),
        ),
    ]
