# Generated by Django 4.2.1 on 2023-05-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_potion_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlcoholVolume',
        ),
        migrations.DeleteModel(
            name='SugarVolume',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name_eng',), 'verbose_name': 'Категория напитка', 'verbose_name_plural': 'Категории напитков'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name_eng',), 'verbose_name': 'Страна происхождения', 'verbose_name_plural': 'Страны происхождения'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name_eng',), 'verbose_name': 'Гастрономия', 'verbose_name_plural': 'Гастрономия'},
        ),
        migrations.RemoveField(
            model_name='body',
            name='description',
        ),
        migrations.RemoveField(
            model_name='body',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='body',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='body',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='body',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='body',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='category',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='category',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='category',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='category',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='color',
            name='description',
        ),
        migrations.RemoveField(
            model_name='color',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='color',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='color',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='color',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='color',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='country',
            name='description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='country',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='country',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='country',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='country',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
        migrations.RemoveField(
            model_name='food',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='food',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='food',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='food',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='food',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='potion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='potion',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='potion',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='potion',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='potion',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='potion',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='productionmethod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productionmethod',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='productionmethod',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='productionmethod',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='productionmethod',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='productionmethod',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='region',
            name='description',
        ),
        migrations.RemoveField(
            model_name='region',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='region',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='region',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='region',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='region',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='type',
            name='description',
        ),
        migrations.RemoveField(
            model_name='type',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='type',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='type',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='type',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='type',
            name='namerus',
        ),
        migrations.RemoveField(
            model_name='variety',
            name='description',
        ),
        migrations.RemoveField(
            model_name='variety',
            name='descriptioneng',
        ),
        migrations.RemoveField(
            model_name='variety',
            name='descriptionfra',
        ),
        migrations.RemoveField(
            model_name='variety',
            name='nameeng',
        ),
        migrations.RemoveField(
            model_name='variety',
            name='namefra',
        ),
        migrations.RemoveField(
            model_name='variety',
            name='namerus',
        ),
        migrations.AddField(
            model_name='body',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='body',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='body',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='body',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='body',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='body',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='color',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='color',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='color',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='country',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='country',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='country',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='potion',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='potion',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='potion',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='potion',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='potion',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='potion',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='productionmethod',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productionmethod',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productionmethod',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='productionmethod',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productionmethod',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='productionmethod',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='region',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='region',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='region',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='type',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='type',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='type',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='variety',
            name='description_eng',
            field=models.TextField(blank=True, db_column='description_eng', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='variety',
            name='description_fra',
            field=models.TextField(blank=True, db_column='description_fr', default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='variety',
            name='description_rus',
            field=models.TextField(blank=True, db_column='description_rus', default=None, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='variety',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='variety',
            name='name_fra',
            field=models.CharField(db_column='name_fr', db_index=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='variety',
            name='name_rus',
            field=models.CharField(db_column='name_rus', db_index=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AddConstraint(
            model_name='body',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng'), name='body_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng'), name='brand_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng'), name='category_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng', 'type'), name='color_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng'), name='country_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng'), name='food_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng', 'brand'), name='man_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='potion',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng', 'year', 'region', 'manufacturer'), name='potion_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='productionmethod',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng'), name='prod_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng'), name='raw_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng', 'country'), name='reg_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng', 'category'), name='subcategory_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='type',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng', 'subcategory'), name='type_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='variety',
            constraint=models.UniqueConstraint(fields=('name_rus', 'name_eng'), name='var_unique_index'),
        ),
    ]
