# Generated by Django 4.2.1 on 2023-05-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_delete_alcoholvolume_delete_sugarvolume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='potion',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productionmethod',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='name_eng',
            field=models.CharField(db_column='name_eng', db_index=True, default='default', max_length=255, verbose_name='name'),
        ),
    ]
