# Generated by Django 4.2.1 on 2023-05-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0021_body_url_brand_url_category_url_color_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='url',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='color',
            name='url',
        ),
        migrations.RemoveField(
            model_name='country',
            name='url',
        ),
        migrations.RemoveField(
            model_name='food',
            name='url',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='url',
        ),
        migrations.RemoveField(
            model_name='potion',
            name='url',
        ),
        migrations.RemoveField(
            model_name='productionmethod',
            name='url',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='url',
        ),
        migrations.RemoveField(
            model_name='region',
            name='url',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='url',
        ),
        migrations.RemoveField(
            model_name='type',
            name='url',
        ),
        migrations.RemoveField(
            model_name='variety',
            name='url',
        ),
        migrations.AddField(
            model_name='body',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='brand',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='category',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='color',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='country',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='food',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='potion',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='productionmethod',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='region',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='type',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='variety',
            name='uri',
            field=models.URLField(blank=True, db_column='uri', null=True, verbose_name='url'),
        ),
    ]
